# .github/workflows/sonar.yml
name: Sonar Scan

on:
 workflow_call:

jobs:
  sonar:
    runs-on: java_build
    #needs: build  # Ensures Sonar runs after build succeeds
    steps:
      - name: SonarCloud Scan
        run: mvn sonar:sonar -Dsonar.projectKey=Madhavi6_DevSecops_Pipeline -Dsonar.organization=madhavi6 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=6e6726b76f510ed2c9111f52788cb193175c6fce
